### ISSUE TITLE
[spec draft] CSS Next structuring

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/css#1]
Based on our next try on CSS Next, we should be able to build new components as modular as we had before, but much easier and with better API.

I think Scratch approach for variables was very useful to generate new project's styleguide easily with reconfiguring stuff.

Now, CSS approach can be exactly the same, only syntax is very different.

You can see [CSS variables reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and [CSSNext features](http://cssnext.io/features/)

Defining colors can be like that:
```css
/* file: colors.css */
:root {
  --primary: pink;
  --primary-contrast: white;

  --secondary: rgba(255, 255, 255, 0.5);
  --secondary-contrast: black;
}

/* file: navbar/lib/style.css */
:root {
  --navbar-color: var(--primary-contrast);
  --navbar-background: var(--primary);
}

.navbar {
  color: var(--navbar-color);
  background: var(--navbar-background);
}
```

Reference: https://github.com/vigour-io/scratch/blob/develop/lib/config/colors.less

_Copied from original issue: vigour-io/front-end#13_

**Comment by nikoloza** [comment]
Responsive things:

```css
/* file: breakpoints.css */
:root {
  --phone: 320px;
  --phone-landscape: 480px;

  --tablet: 768px;
  --tablet-landscape: 1024px;

  --screen-small: 1280px;
  --screen-medium: 1366px;
  --screen-big: 1680px;

  --tv: 1920px;
}
```

Reference: https://github.com/vigour-io/scratch/blob/develop/lib/config/breakpoints.less
